- codegen/codegen_outofplacebatching.py
- functorch/csrc/BatchRulesBinaryOps.cpp
- functorch/csrc/BatchRulesConv.cpp
- functorch/csrc/BatchRulesHelper.cpp
- functorch/csrc/BatchRulesHelper.h
- functorch/csrc/BatchedFallback.cpp
- functorch/csrc/BatchingMetaprogramming.h
- functorch/csrc/DynamicLayer.cpp
- functorch/csrc/OutOfPlacePlumbing.cpp
- functorch/csrc/PythonKey.cpp
- test/test_vmap.py
Also fixes https://github.com/zou3519/functorch/issues/8
Currently doesn't support the case where bias is batched but neither the input/weights are batched.
> Added conv2d batching rule

- functorch/csrc/BatchRulesLinearAlgebra.cpp
- functorch/csrc/DynamicLayer.cpp
- test/test_vmap.py
This PR makes it so that dispatch on kBatchedKey only can happen if there are
tensors batched at the current level. Otherwise, kBatchedKey is excluded
(even if there are BatchedTensors!).
To find tensors batched at the current level, we check:
- all tensor arguments
- we peek into all TensorLists
- we peek into all Tensor?[].
the above bullet points should be sufficient.
Dispatch for kVmapModeKey is not affected.
Test Plan:
- run all tests
> Selectively enable dispatch on kBatchedKey

- functorch/csrc/TensorWrapper.cpp
- functorch/csrc/TensorWrapper.h
- test/test_eager_transforms.py
- test/test_ops.py
TensorWrapper can have storage now:
- Case 1: If it wraps a tensor with storage, it will have storage
- Case 2: If it wraps a tensor without storage, it will not have storage
The rationale for this is to fix #7. When torch.tensor gets called, the
following happens:
- at::empty gets called
- some data from a PyObject* gets written directly into the new empty
tensor
The previous problem was that `at::empty` would return a TensorWrapper
wrapping a regular Tensor and that TensorWrapper did not have
storage/data_ptr.
It should be fine that TensorWrapper sometimes has storage. Users should
not write directly to the .data_ptr (because that would cause gradients
to be incorrect, but it is the same in regular PyTorch).
Test Plan:
- wait for tests
> (Grad)TensorWrapper sometimes has storage (and data_ptr)

- functorch/csrc/BatchRulesViews.cpp
- functorch/csrc/BatchingRegistrations.cpp
- test/test_vmap.py
Addresses #27 by updating `squeeze` and `squeeze.dim` to the new batching rules style while also adding special casing for scalar arrays to match underlying PyTorch behavior.
> Updated squeeze and squeeze.dim batching rules to new style [#27]

- functorch/csrc/BatchRulesModules.cpp
- functorch/csrc/BatchRulesScatterOps.cpp
- test/test_vmap.py
The one hot decomposition is a quick hack for #85. I think we might
want to make one_hot a primitive w.r.t. autograd because of the
data-dependent error checking.
Test Plan:
- wait for CI
> Adds one_hot decomposition, scatter batch rule

- functorch/_src/python_key.py
- test/test_pythonkey.py
Benchmark:
https://gist.github.com/zou3519/f7691a94f8570b27cccc8e16fc8ed13b
It doesn't look like this adds a lot of overhead. If the overhead
becomes a problem we can move this into C++.
The cache works by specializing on shape/stride/dtype/device of the
input tensor and any concrete values.
NB: the concrete value cache means that if an integer arg to the
function changes, we will recompile. In the future, when we add
static_argnums, we should change the cache to "not specialize on
specific integers".
Test Plan:
- run tests
> Specialization cache

- functorch/csrc/BatchRulesViews.cpp
- functorch/csrc/BatchingRegistrations.cpp
- setup.py
Description:
- Tried to port `_reshape_alias` to the new API. Algorithm is not exactly the same as in the old method, maybe unsafe ?
cc @zou3519
> Ported `_reshape_alias` to the new API

- functorch/csrc/BatchRulesReduceOps.cpp
- functorch/csrc/OutOfPlacePlumbing.cpp
functorch was failing when trying to run on the latest PyTorch.
This [PR](https://github.com/pytorch/pytorch/pull/65242) changed the signature of `softmax` and `logsoftmax` backward functions and hence there was a failure while Registering.
I think this will pass once the nightly with changes from this PR is pulled by the CI.
> {log|softmax}_backward update as per the new signature

- .circleci/unittest/linux/scripts/install.sh
This PR can be reverted once PyTorch is relanded log_softmax PR.
More details: https://github.com/facebookresearch/functorch/pull/160#issuecomment-932389442
> temporary fix pth version to make CI pass

- functorch/_src/eager_transforms.py
- functorch/csrc/DynamicLayer.cpp
- functorch/csrc/DynamicLayer.h
- functorch/csrc/init.cpp
- test/test_eager_transforms.py
Fixes https://github.com/facebookresearch/functorch/issues/13
Case 1: grad gets called inside torch.no_grad.
- grad should ignore torch.no_grad because it's "creating a new level of
autograd above the current level"
- Another way to think about this is that grad(f) is a "function
transform": its result should not be affected by context managers that
are outside of the function f
Case 2: torch.no_grad gets called inside `grad`
- grad should respect torch.no_grad
See NOTE [grad and vjp interaction with no_grad] for implementation
strategy. It unfortunately involves a mode.
Test Plan:
- Many tests
> no_grad fix

- functorch/csrc/BatchRulesReduceOps.cpp
- test/test_vmap.py
`aminmax` has a different behavior compared to other reduction ops for scalar tensor.
```python
t = torch.randn(())
result = torch.aminmax(t, dim=0, keepdim=True)
print(result[0].shape, result[1].shape)
result = torch.sum(t, dim=0, keepdim=True)
print(result.shape)
```
Output
```
torch.Size([1]) torch.Size([1])
torch.Size([])
```
Due to this we can't use `REDUCTION_BOXED_ARGS` as is (due to the following lines).
https://github.com/facebookresearch/functorch/blob/17f407c9faea3ec5f953b9afb17d7c8c7e6f34fb/functorch/csrc/BatchRulesReduceOps.cpp#L162-L164
For this reason, have added a batching rule. Other option would be to update `REDUCTION_BOXED_ARGS` to accommodate this case.
> add aminmax batching rule

- benchmarks/operator_authoring.py
- functorch/__init__.py
- functorch/_src/operator_authoring.py
- functorch/csrc/CompileCache.cpp
- functorch/csrc/CompileCache.h
- functorch/csrc/init.cpp
- test/test_operator_authoring.py
The main problem was missing handle_torch_function_no_python_arg_parser from the main API.  This PR also adds the handling for backward.
> Re-land the compile cache

- README.md
- functorch/_src/eager_transforms.py
Adds docstring for jacrev for #224, also does some minor cleanup of the readme in the `jacrev` section and removes a broken example
> add jacrev docstring

- functorch/csrc/BatchRulesModules.cpp
- test/test_ops.py
Description:
- Added backward batch rule for pad replicate/reflect modes
> Added backward batch rule for pad replicate/reflect modes

- functorch/csrc/BatchRulesDecompositions.cpp
- functorch/csrc/BatchRulesPooling.cpp
- test/test_ops.py
- test/test_vmap.py
Description:
- Added batch rule for adaptive_avg_pool{1d,2d,3d} and avg_pool{1d,2d,3d}
- Enabled tests for adaptive_avg_pool{1d, 2d, 3d}, avg_pool{1d,2d,3d} and nn.functional.interpolate (mode="area")
Adresses #240
> Added batch rule for (adaptive_)avg_poolNd

- functorch/_src/eager_compilation.py
- functorch/_src/memory_efficient_op_authoring.py
- functorch/_src/python_key.py
- functorch/compile/__init__.py
I refactored the graph partitioner to extract a subgraph with given inputs and outputs. In particular, it allows for inputs that aren't one of the graph placeholders.
So, for example, to save the mask, we simply find the dropout nodes, append them to the list of "saved nodes", and then call
```
fw_graph = _extract_graph_with_inputs_outputs(joint_module.graph, primal_nodes, fwd_outputs + saved_values)
bw_graph = _extract_graph_with_inputs_outputs(joint_module.graph, saved_values + tangent_nodes, bwd_outputs)
```
> [AOT Autograd] refactor partitioner to extract arbitrary graph given inputs and outputs

- functorch/csrc/BatchRulesDecompositions.cpp
- functorch/csrc/BatchRulesModules.cpp
- test/test_ops.py
- test/test_vmap.py
Description:
- Added im2col batch rule and enabled vmap for nn.functional.unfold op
Using `EXISTING_BDIM` macro to put bdim into 0 as im2col expects dim=0 to be the batch dim
Additionally moved `OP_DECOMPOSE(nll_loss*)` into alphabetical order.
> Added im2col batch rule and enabled vmap for nn.functional.unfold op

- test/functorch_additional_op_db.py
Fix renaming: sample_inputs_hardshrink_hardtanh -> sample_inputs_softshrink_hardshrink_hardtanh
by https://github.com/pytorch/pytorch/pull/68521
CI report: https://app.circleci.com/pipelines/github/pytorch/functorch?branch=pull%2F288
> Fix method rename and fix again the CI

- functorch/csrc/BatchRulesViews.cpp
- functorch/csrc/BatchedTensorImpl.cpp
- functorch/csrc/BatchedTensorImpl.h
- functorch/csrc/BatchingRegistrations.cpp
- test/common_utils.py
- test/test_ops.py
This PR depends on some fixes in core to land, so we expect CI to fail here for now
This PR:
- Updates `jvp` to support multiple inputs and outputs
- Fixes batched tensor storage offset to be the same as the wrapped tensor
- Adds per-op test for `jvp` by comparing with just normal forward AD in core
- Adds per-op test for `vmap(jvp` by comparing the looped version with batched version
cc @albanD @zou3519 @Chillee
> Add per-op tests for jvp and vmap + jvp

- functorch/csrc/BatchRulesModules.cpp
- test/test_vmap.py
Reference: https://github.com/pytorch/functorch/issues/240
> [batching] pixel_{un}shuffle

- functorch/csrc/DynamicLayer.cpp
- test/test_eager_transforms.py
Fixes https://github.com/pytorch/functorch/issues/303
ThreadLocalDebugInfo stores a shared_ptr to some TLS that is shared
between ALL threads. The behavior of FuncTorchTLS should be that each
thread has its own TLS.
Test Plan:
- new test
> Use FuncTorchTLSBase instead of ThreadLocalDebugInfo

- functorch/csrc/BatchRulesBinaryOps.cpp
- test/test_ops.py
- test/test_vmap.py
Description:
- Added addr op decomposition
> Added addr op decomposition

- functorch/_src/aot_autograd.py
- functorch/_src/memory_efficient_op_authoring.py
- functorch/csrc/CompileCache.cpp
- test/test_compile_cache.py
Replacing with single cache. This one removes the use of templates to have a single cache, which is much easier to control. 
The key of the cache is of type string, which is built by naively concatenating all the private members of the SpecializationKey class (either Dynamic or Static for now).
Some of the missing items before merging
* Testing the latency. String building might make look up slow.
> Single cache

- functorch/_src/fx_minifier.py
- functorch/compile/__init__.py
Often, compilation fails on a large FX graph. Finding a minimal example is quite tedious, so this minimizer automatically tries to find the minimum graph that still fails. It does 2 main strategies:
Does 2 main strategies:
1. Truncates suffix: Removes some suffix from the graph and sets a new output.
2. Delta Debugging: Tries replacing half of the graph with inputs. If fails, tries replacing quarter of the graph, etc.
This is an example usage, will post example minimization in a comment
```
from functorch.compile import minimizer
def pass_checker(f, inps):
try:
nf = torch.jit.script(fx.symbolic_trace(f))
for _ in range(5):
nf(*inps)
except Exception as e:
return False
return True
inps = [torch.randn(i, device='cuda') for i in inps]
with torch.jit.fuser("fuser2"): …
```
> Added autominifier for FX graphs

- test/test_ops.py
Previously they were not vmapping over non-differentiable arguments.
That case is important to test.
Test Plan:
- run tests
> Fix vmapvjp tests

- functorch/csrc/BatchRulesConvolution.cpp
- test/test_ops.py
This is the most ridiculous batching rule we have.
Featuring a guest appearance of efficient zeros tensors.
We should really consider upstreaming einops.rearrange
(https://einops.rocks/api/rearrange/). Many batching rules are straight
up dimension manipulation and if we could specify that with strings we'd
be done 10x faster.
Test Plan:
- run tests
> convolution_backward batch rule

- functorch/csrc/BatchRulesDecompositions.cpp
Before this change `include_guard` declaration can be interpreted as both local variable declaration and function prototype
Disambiguate it by using curly bracket
> Fix parameter declarator cannot be qualified error

- functorch/csrc/BatchRulesScatterOps.cpp
- functorch/csrc/BatchedFallback.cpp
- test/functorch_additional_op_db.py
- test/test_ops.py
- test/test_vmap.py
Fixes https://github.com/pytorch/functorch/issues/363
This PR:
- adds a batch rule for _index_put_impl_
- fixes the index_put_ batch rule
- adds a new OpInfo so we can actually test this
- fixes the fallback paths to error out on Tensor?[], otherwise they are
very wrong.
> Fix getitem

- functorch/_src/aot_autograd.py
- functorch/csrc/CompileCache.cpp
- test/test_compile_cache.py
The non tensor args are hashed in python and sent to the cache. Currently, all the non tensor args are cached.
@Chillee
> [Compile Cache] Handle non tensor args

- functorch/csrc/BatchRulesConvolution.cpp
Why?
- efficient zeros tensor doesn't have efficient implementation for
convolution_backward yet
- allocating an empty tensor on CUDA doesn't actually launch any
kernels (as compared to a zero-filled tensor)
> Use empty tensor instead of efficient zeros tensor

- functorch/_src/aot_autograd.py
- functorch/csrc/CompileCache.cpp
- test/test_compile_cache.py
For same function, we might want to benchmark different compilers. Previously, compile cache was not caching the compilers. This PR caches the ids of fwd and bwd compilers.
@Chillee
> [Compile Cache] Caching the forward and backward compiler ids

- README.md
- setup.py
trying the examples it requires `networkx`.
If it's an optional requirement, could we then perhaps have some sort of `extras` group like:
```
pip install -e .[all]
```
which will then get all the requirements, including the optional ones?
```
extras = {}
extras["all"] = ["networkx", ...]
setup(
...
extras_require=extras,
```
e.g. you can see how it's being used [here](https://github.com/huggingface/transformers/blob/master/setup.py#L367)
> [requirements] missing networkx

- functorch/_src/eager_transforms.py
- test/test_eager_transforms.py
Description:
- Enabled pytree of tensors output for jvp, jacfwd
- Added tests
Now we can do
```python
import torch
import functorch as ft
def sum_parabola(x):
res = (2 * x**2 + 3 * x + 4).sum()
return res, {"res": res}
x = torch.tensor([1., 1.5])
t = torch.tensor([2., 2.5])
out = ft.jvp(sum_parabola, (x,), (t,))
print("-- out ft vjp sum_parabola: ", out)
x = jnp.array([1., 1.5])
t = jnp.array([2., 2.5])
out = jax.jvp(sum_parabola, (x,), (t,))
print("-- out jax jvp sum_parabola: ", out)
x = torch.tensor([1., 1.5])
out = ft.jacfwd(sum_parabola)(x)
print("-- out ft jacfwd sum_parabola: ", out)
x = jnp.array([1., 1.5])
out = jax.jacfwd(sum_parabola)(x)
print("-- out jax jvp sum_parabola: ", out)
> 
-- out ft vjp sum_parabola:  ((tensor(22.), {'res': tensor(22.)}), (tensor(36.5000), {'res': …
```
> Enabled pytree of tensors output for jvp, jacfwd

- functorch/csrc/BatchRulesDecompositions.cpp
- functorch/csrc/BatchingRegistrations.cpp
I really need this to unify the codegen.
> Excise a bunch of legacy batch rules that could be decompositions

- functorch/_src/eager_transforms.py
- test/test_eager_transforms.py
Description:
- Enabled any type of aux output (previously, aux could be only pytree tensors due to `aux = _undo_create_differentiable(aux, level)`)
- Parity with JAX API:
```python
import jax.numpy as jnp
import jax
def f(x):
return (x * 2).sum(), "abc"
x = jnp.array([1., 1.5])
out = jax.grad(f, has_aux=True)(x)
>
(DeviceArray([2., 2.], dtype=float32), 'abc')
```
> Enabled any type of aux output

- functorch/_src/eager_transforms.py
- test/test_eager_transforms.py
Reverts pytorch/functorch#423
We have to more about testing #423 and the implications it could have. Let's keep aux output as tensor for now
> Revert "Enabled any type of aux output"

- functorch/csrc/CompileCache.cpp
- test/test_compile_cache.py
@Chillee What do you think here? This is little ugly but better than doing it in C++.
~~Basically, we send only the non-None args to the cache. Our cache supports scenario where same function can have different number of arguments. So, it recompiles when it all args are Tensor the next time.~~
Update - I changed this to C++ because, as Horace pointed out, it does not work in all cases.
> [Compile Cache] Dont pass None args to Compile Cache

- functorch/_src/compilers.py
This causes some problems about input shape.
> Fix typo of `memory_efficient_fusion` parameter

- functorch/csrc/OutOfPlacePlumbing.cpp
Because of [this PR on core](https://github.com/pytorch/pytorch/pull/61439), our out of place plumbing for `gelu` + `gelu_backwards` will break tomorrow (it looks like this didn't make it into Feb 14 nightly). This updates the out of place plumbing to fix this. If this doesn't break current nightly, I'll land it today so the only problem will be the decompositions tomorrow
> Update OutOfPlacePlumbing because of new kwarg in gelu

- functorch/csrc/BatchRulesDecompositions.cpp
- test/common_utils.py
- test/test_ops.py
- test/test_vmap.py
Instance norm just decomposes to batch norm so the batch rule itself is simple. However, because it also takes running_mean and running_var as inputs, the sample inputs needed to have the same restrictions as the batch norm ones (if the input is batched, running mean and running var must be batched).
This got a little weird because when running_mean and running_var are both None, it should be fine for the input to be batched or not (we aren't updating anything). However, the implementation of instance norm created a new tensor in that case. This leaves a TODO explaining what's happening but it will need to be fixed in pytorch/pytorch
> Add instance norm (+ backward)

- .circleci/unittest/linux/scripts/environment.yml
A surprisingly simple fix, sad that I didn't catch it earlier. Basically the newer versions are released under this name instead of `xmlrunner`. Newer versions support highlighting "unexpected success" as a failure. An example of what this looks like is [here](https://app.circleci.com/pipelines/github/pytorch/functorch/1456/workflows/cf17b90e-3505-46d6-80b3-197239dd65f4/jobs/8732).
Should make debugging main CI take on the order of one commit instead of 2
> Fix unexpected success not getting highlighted in CI

- functorch/_src/compilers.py
Handling empty list Torchscript bugs for 2 operators
* `new_empty`
* `avg_pool2d_backward` - handle empty strides
> [AOT Autograd] FX graph modifications to avoid Torchscript bugs

- functorch/_src/vmap.py
- test/test_vmap.py
Description:
- Added temporary odict pytree registration
- combine_state_for_ensemble can work on torchvision segmentation models
Related to https://github.com/pytorch/functorch/issues/445#issuecomment-1050946177
Logs : 
```
python -u check_combine_state_for_ensemble_on_tv_segm_models.py 
Torch: 1.12.0.dev20220223+cu111
torchvision: 0.13.0.dev20220223+cu111
Functorch: 0.2.0a0+c8b640c
-- Check fcn_resnet50 model
/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:1279: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::dropout. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at  /ft/functorch/csrc/BatchedFallback.cpp:83.)
return _VF.dropout_(input, p, training) if inplace …
```
> Added temporary odict pytree registration

- functorch/_src/python_key.py
- functorch/compile/__init__.py
- test/test_pythonkey.py
Instead of saying that a PythonTensor has a regular (e.g., CPU) tensor
and an FX proxy, a PythonTensor *is a* regular CPU tensor, that also
carries an FX proxy (that updates as we go along).
Partially addresses https://github.com/pytorch/functorch/issues/465 and
it also fixed some expected failures in the test suite.
> Don't unnecessarily wrap the elem in PythonTensor

- functorch/csrc/DynamicLayer.cpp
- test/test_vmap.py
Loud error message on #207 
The potentially hot take baked in here is that we should never allow the use of autograd.Function under any of the transforms. This is going conservative because the following works:
```
class MyReLu(torch.autograd.Function):
...
def bar(x):
return x.clamp(0)  # assume that foo and bar do the same thing
def foo(x):
return MyReLu.apply(x)
x = torch.tensor(4.)
grad(bar)(x))  # produces (1.)
grad(foo)(x)   # produces (1.) the same thing
```
the reason for being conservative is because if we have instead
```
x = torch.tensor(4., requires_grad=True)
grad(bar)(x))  # produces (1., grad_fn=<...>)
grad(foo)(x)   # produces (1.)
```
since the grad fn is null when using autograd.Function but not when it's not using it, a user could end up with incorrect results if they …
> Error on any use of autograd.Function

- functorch/csrc/BatchRulesRandomness.cpp
- functorch/csrc/VmapModeRegistrations.cpp
- test/test_vmap.py
Adds batching rules for cauchy_, exponential_, geometric_, log_normal_, and uniform_
Since they all use the same inplace random logic and they're each so small, I just put them all together
> inplace random batching rules

- docs/source/index.rst
- docs/source/install.rst
- docs/source/ux_limitations.rst
- notebooks/whirlwind_tour.ipynb
I modified the docs website:
- It has a new install page which we'll fill out l ater
- It has a new "whirlwind tour" section which is just our README
copy-pasted
- It has a "UX Limitations" section describing arbitrary python
mutation, in-place operations, and control flow.
Please let me know if you think anything else should be here.
Future work:
- I might put up a table of what operators we have support for and
which ones we don't, autogenerated via OpInfo
> Docs website modification

- functorch/csrc/DynamicLayer.cpp
- test/test_ops.py
It turns out we've had this problem since the beginning of the time but
it wasn't causing any problems. This PR makes it so that after a
transform, like grad(f)(x), the DynamicLayer{Front, Back}Mode keys are
properly disabled.
> Fix not cleaning up DynamicLayer dispatch keys after transforms.

- functorch/_src/python_key.py
- test/test_pythonkey.py
The following test snippet fails accuracy testing. There is a broader issue here first (not handled by this PR) - mutation. The joint graph had an inplace op. And partitioner decided to recompute the inplace op, leading to incorrect gradients.
The second issue is that, in the test below, we are using default partitioner. Default partitioner is not supposed to recompute any operations in the backward pass. So, this PR specifically handles the second issue. We were not recording the meta tensor knowledge for inplace ops, causing redundant recomputation.
Note that the first issue still exists and is very likely to happen (recomputation of inplace ops) in the specialized partitioners  like min-cut rematerialization partitioner. 
~~~~
import functorch
import torch
from functorch.compile import …
> Setting tensor_meta attr for inplace ops

- README.md
Caught a minor typo in the docs:
returns a ```few``` function, changed to ```new``` for clarity
> update typo in README.md

- functorch/csrc/BatchRulesBinaryOps.cpp
- functorch/csrc/BatchRulesRandomness.cpp
These were from @zou3519's comments on the PRs that I missed as I was trying to get everything in. It's ~4 tiny changes split up into commits:
- fixes 2 instances of `shapeVec` that were still doing O(n) insertion
- removes unnecessary unsqueeze
- adds comment explaining the cases in binary randomness
- corrects the inplace error message to say bernoulli, not arithmetic
> Make a number of small changes to randomness

- functorch/csrc/VmapGeneratedPlumbing.h
- tools/codegen/gen.py
- tools/codegen/gen_vmap_plumbing.py
Here's how the output looks:
- https://github.com/pytorch/functorch/blob/main/functorch/csrc/VmapGeneratedPlumbing.h
- (yes, we check in the codegen as a short-term solution because we
didn't have time to add it as a step to setup.py)
short-term / long-term plans
- we've copy-pasted tools/codegen from pytorch/pytorch into functorch
- In the long term, pytorch/pytorch will package its codegen somehow
(https://github.com/pytorch/pytorch/issues/73212)
Questions for reviewer:
- Are we using PyTorch's codegen abstractions the right way?
> vmap codegen, for review

- .github/workflows/docs.yml
Description:
- Added GHA "docs deploy" job based on "build-docs" job
- Using an "action" to commit and push to the branch.
- use `git reset --soft <fixed-commit>` to squash history
- History on gh-pages: https://github.com/vfdev-5/functorch/commits/gh-pages
- Runned GHA that pushed to gh-pages on my fork:
- https://github.com/vfdev-5/functorch/actions/runs/1888876266
Fixes #500
> Added docs deployment step in GHA

- functorch/compile/__init__.py
> Make default_decompositions visible in functorch.compile namespace

- functorch/_src/decompositions.py
- test/test_ops.py
Signed-Off-By: Prateek Gupta <prateek@nod-labs.com>
> Add decomposition for aten.native_layer_norm_backward op.

- test/test_ops.py
- test/xfail_suggester.py
Failures are either:
- lack of PyTorch forward-mode AD support (mostly)
- efficient zero tensors errors
- CUDA asserts (really need to be investigated).
All of the problems should be reproducible on the pytorch/pytorch side.
> jvp x vjp testing

- functorch/csrc/BatchRulesNorm.cpp
- test/test_ops.py
Fixes #622 
Also adds scaffolding for tests that use opinfo and call autograd.grad but since autograd.grad can't ask for the derivative with respect to a batched tensor since all inputs must require_grad, we had to add a hack to get around the case where none of the remaining inputs require grad
> Fix group norm and add scaffolding for autograd.grad tests

- functorch/_src/eager_transforms.py
- test/test_eager_transforms.py
fixed a bug where input mutations weren't getting propagated to the inputs correctly
> fix functionalize(): properly propagate input mutations

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- docs/requirements.txt
- setup.py
Makes doc build + lint check run on release/0.1 branch
Also cleans up the problems for those jobs that currently break them (since they were small changes)
> fix release branch

- functorch/_src/aot_autograd.py
- test/test_pythonkey.py
Currently the AOT Autograd assumes that the forward outputs and corresponding input gradients have same strides, but thats not always true. In this PR, we force both the forward outputs and corresponding input gradients to be contiguous. 
This is suboptimal as we will call `contiguous()` when it might not be necessary. For now, we want to go ahead with the current solution, even though it might be suboptimal, because other solutions are somewhat tricky and require some overhead experiments. Tracked at #537
> Trace the backward pass assuming contiguous tensors

- functorch/csrc/BatchRulesActivation.cpp
- test/test_ops.py
- test/test_vmap.py
Adds the batching rule for prelu. Will need to wait on merging of [prelu opinfo fix](https://github.com/pytorch/pytorch/pull/74467) in order to get rid of the last commit that does a hacky fix so that the weight is passed as a positional arg and is therefore batchable
> Prelu batching rule (forward + backward)

- functorch/_src/aot_autograd.py
- functorch/compile/__init__.py
- test/test_pythonkey.py
This PR adds a new API - `aot_module_simplified` which removes the overhead associated with pytree and compilation cache for TorchDynamo-like frontends generated graphs.
For completeness, I am adding few benchmarks
~~~
import functorch
import torch
from functorch.compile import aot_module_simplified, aot_module, nop
from time import perf_counter
class MockModule(torch.nn.Module):
def __init__(self):
super().__init__()
self.linears = torch.nn.Linear(10, 10)
def forward(self, x):
return (x, )
mod = MockModule()
x = torch.randn(4, 5)
mod(x)
aot_mod = aot_module(mod, nop)
aot_mod_simple = aot_module_simplified(mod, nop)
def bench(m):
for _ in range(50):
m(x)
t0 = perf_counter()
repeats = 1000
for _ in range(repeats):
m(x)
t1 = perf_counter()
return f"{round((t1 - t0) * (10**6)/repeats, 2)} …
> AOT Module Simplified - Low Overhead version of AOT Module

- functorch/_src/aot_autograd.py
> Disbale torchdynamo on AOT Autograd generated graphs

- functorch/_src/decompositions.py
- test/test_ops.py
The return type for native_layer_norm_backward is a tuple of
optional tensors as the output_mask decides whether or not the
gradient of a particular input is to be calculated or not.
Signed-Off-By: Prateek Gupta <prateek@nod-labs.com>
> Fix the decomposition of native_layer_norm_backward operation.

- functorch/csrc/BatchRulesBinaryOps.cpp
- test/test_vmap.py
Same as #670 (naming was incorrect in that PR 🤦‍♀️ )
This only ports the binomial fix because the normal fix was something that was fixed on the testing side. Additionally this only adds one test of the many combinations (any with the second tensor arg having a last batch dim) that failed in the original testing
> [Release] Fix binomial (#670)

- functorch/csrc/BatchRulesUnaryOps.cpp
- functorch/csrc/BatchingRegistrations.cpp
The to(self, other) batching rule doesn't actually handle the case where
self is not Batched and other is Batched.
> Fix to batching rule

- functorch/csrc/DynamicLayer.cpp
- functorch/csrc/DynamicLayer.h
- test/test_eager_transforms.py
And change how we handle "default PyTorch autograd". The motivation behind this is that previously we special-cased a lot of things (e.g. PythonTLSSnapshot, autograd) and this PR cleans some of those special cases up.
> Refactor DynamicLayer TLS logic

- functorch/csrc/BatchedTensorImpl.h
- functorch/csrc/CustomFunction.cpp
- functorch/csrc/DynamicLayer.h
- functorch/csrc/Macros.h
- functorch/csrc/TensorWrapper.h
- functorch/csrc/VmapTransforms.h
- setup.py
Previously we were using TORCH_API, which doesn't actually mean much for
us because it is always set to import (windows) or default visibility
(gnu). This PR changes it so that FUNCTORCH_API is set to export/import
(windows) correctly.
> Fix visibility macros

- functorch/csrc/CustomFunction.cpp
- functorch/csrc/CustomFunction.h
- functorch/csrc/init.cpp
- test/test_eager_transforms.py
I think libtorch_python does not have visibility macros set correctly
for windows, so this PR guards our custom_vjp implementation (which
relies on some C++ bits from libtorch_python).
We'll either fix libtorch_python or actually write a better version of
custom_vjp in the future.
> Macro-guard the custom_vjp prototype from windows

- functorch/_src/eager_transforms.py
- functorch/csrc/DynamicLayer.cpp
- functorch/csrc/DynamicLayer.h
- functorch/csrc/init.cpp
- test/test_eager_transforms.py
This PR goes with the core-side change here: https://github.com/pytorch/pytorch/pull/75302, which updates the functionalization pass to be able to turn view ops into view_copy ops. Mobile mentioned that they would like to be able to use the `functionalize()` transform to trace models for running on mobile, and removing view ops (cc @ZolotukhinM)
This PR updates `functionalize()` to be toggleable: `functionalize(remove='mutations')` (the default) will remove mutations but preserve views. `functionalize(remove='mutations_and_views')` will remove mutations, and additionally convert `view` operators into their corresponding `view_copy` operators.
Some extra stuff in the PR:
- added more testing for out= mutations, which I fixed in a corresponding core PR: …
> functionalize(): make "additionally removing views" toggleable

- test/test_eager_transforms.py
@bdhirsh It looks like this stopped applying the detach. This might be from an upstream change but just wanted to make sure that this doesn't look like a bug
> Fix functionalize-aot autograd test

- functorch/_src/eager_transforms.py
- test/test_eager_transforms.py
`functionalize()` would always assume that the output of the function call was a `FunctionalTensorWrapper` that it should unwrap.
That isn't true though if you have a function that just returns a global tensor, because we have no way to ensure that it gets wrapped at any point.
Fixes the `tensor_constant` repro example from https://github.com/facebookresearch/torchdynamo/issues/88. With this patch, this runs without error:
```
class FxModule(torch.nn.Module):
def __init__(self):
super().__init__()
self.register_buffer('_tensor_constant1', torch.empty([512], dtype=torch.int64))
def forward(self):
_tensor_constant1 = self._tensor_constant1
return (_tensor_constant1, ) 
print("Starting 4")
mod = FxModule()
def fn4():
return mod()
ref = fn4()
res = functionalize(fn4)()
for t1, t2 in zip(ref, …
```
> functionalize(): properly handle global return tensors

- functorch/_src/decompositions.py
Previously, it required only a single overload be registered to
a packet, if you asked for that packet in decompositions.  But
this is not really necessary; you could easily just return decomps
for all overloads in the packet.  This is strictly more general
and I can't imagine a situation where it's not what you want.
Signed-off-by: Edward Z. Yang <ezyang@fb.com>
> Generalize get_decompositions handling for OpOverloadPackets

- functorch/_src/make_functional.py
- test/test_eager_transforms.py
Related to https://github.com/pytorch/functorch/issues/639#issuecomment-1097154660
Description:
- Added `params_require_grad` argument to `make_functional` and `make_functional_with_buffers`
- Added tests
@samdow let me know if something else I'm missing for this PR. Thanks
> Added params_require_grad arg to make_functional*

- functorch/_src/decompositions.py
Adds decomposition for L1 loss backward
If self and target are of different sizes, it will warn (but not error) in the forward pass. I didn't add this to the backward call since it assumes the user will have seen the warning once during the forward
> L1 loss backward decomposition

- functorch/_src/decompositions.py
Error checks are pulled from [this function](https://github.com/pytorch/pytorch/blob/a079cbca0a0e312017665efa5fae00f24c7305ef/aten/src/ATen/native/LossNLL.cpp#L62)
Decomposition is pulled from batching rule
> NLL Loss backward decomposition

- functorch/csrc/PyTorchOperatorHacks.cpp
- test/test_eager_transforms.py
This should fix #780.
cc @Chillee @zou3519, would it be reasonable to make the `aten::linear` op composite compliant instead, so you don't have to worry about keeping the code in sync from in core? Not 100% sure but I think you can do the same "if isSubclassLike()" stuff in `linear`.
> fix at::linear numeric accuracy for functorch, add test

- functorch/csrc/BatchRulesScatterOps.cpp
- test/test_vmap.py
Fixes #773
Basically what was happening was that when we were only batching on the input tensor, we added None to the start so it became `x[idx]` -> `x[:, idx]`. This is fine until you start nesting vmaps that batch idx where, as the issue found, the batches get misaligned (note that the fake_vmap shape in the issue is also a little off, we default out_dim=0 instead of out_dim=in_dim).
It was tricky to add tests with nested vmaps using the current harness, so I added tests with empty indexing, which can get us the same misaligned behavior as well as the test provided in the issue (with out_dims added to get matching behavior)
> Fix advanced indexing

- functorch/csrc/BatchedTensorImpl.cpp
- functorch/csrc/BatchedTensorImpl.h
Companion PR for https://github.com/pytorch/pytorch/pull/77036
Signed-off-by: Edward Z. Yang <ezyang@fb.com>
> Update for consolidated contiguous/sizes policy

- functorch/_src/eager_transforms.py
- test/test_ops.py
jvpvjp for decompositions was only running one sample per opinfo. This fixes that
This is currently broken since `nll_loss2d_backward` doesn't have actually have a decomposition and this is finally hitting that case for 2 tests
> Make jvpvjp actually run all the tests for decompositions

- test/test_eager_transforms.py
Fixes #799
The fix is a change in core, but I tested that the tests pass locally with  https://github.com/pytorch/pytorch/pull/77358. I'll wait til that PR lands before merging this one.
> fix functioanlization tests

- functorch/_src/decompositions.py
- functorch/_src/eager_transforms.py
- functorch/csrc/DynamicLayer.cpp
- test/test_ops.py
This adds forward over reverse support for layer norm (it needs to be done a little hackily, some explanation is inline. But it has a slightly different decomposition for layer norm backward that shouldn't be used except for this temporary hack so that we can track the input gradients properly)
In doing so, it also generalized some of the binary cross entropy hacks for in_dims and found a small bug in there (the tolerance needed to be a little bigger) so there's some minor fixes around that
> add layer norm support, clean up some binary cross entropy support

- functorch/_src/eager_transforms.py
- test/test_ops.py
This adds tests that have tensors filled with -1000, 0, or 1000 (-1000 and 1000 because it hits inf for exp(-x) or exp(x), respectively) for the functions that use decompositions for forward over reverse coverage
~Currently, there's a bug in the nll loss decomposition that I didn't catch earlier so some of the shapes are commented out (specifically it fails if the weight is 0). I'm working on a fix for that before the branch cut tomorrow~ This bug was coming when weight was all 0s, so we decided that a user should not end up doing this. I'll check that this works with a weight of mostly 0s and a single 1 entry
> Add extremal testing for forward over reverse using decompositions 

- test/test_ops.py
Adds a check to see if the forward over reverse tests where we are using a decomposition should actually be using a custom formula. This way, we can get signal to remove decompositions as the forwards over reverse support gets better
(tested with `nn.functional.linear`, failure does show up with error message: 
`AssertionError: True is not false : nn.functional.linear now supports forward over reverse without a decomposition`)
> [test_jvpvjp] check if custom formula is available

- functorch/_src/eager_transforms.py
- functorch/csrc/BatchRulesBinaryOps.cpp
Remove the `addr` decomposition in `functorch` to use the one in  PyTorch core. 
1. removed the `addr` decomposition in functorch/csrc/BatchRulesBinaryOps.cpp
2. registered the Pytorch core decomposition in functorch/_src/eager_transforms.py. A new register method `_register_jit_decomposition_bypass_script` is implemented to bypass torch script. The existing `_register_jit_decomposition` does not work for `addr` because the Tensor types generated cannot be unioned by torch script.
>  Replace addr_decomp with the one in PyTorch Core, issue #833

- functorch/csrc/Interpreter.cpp
- test/test_eager_transforms.py
Fixes https://github.com/pytorch/functorch/issues/842
The Diagnosis
=============
As Brian pointed out:
For jvp(sub, ...), the chain of dispatch should be:
```
DynamicLayerFrontMode -> at::sub autograd kernel -> DynamicLayerBackMode
```
Instead, what we're doing today is
```
JVP dynamic layer -> at::sub autograd kernel -> at::sub zero_kernel
```
(the zero_tensor kernel errors out, because the inputs are
BatchedTensorImpl objects)
The Problem
=============
functorch's behavior on dispatch keys between DynamicLayerFrontMode and
DynamicLayerBack mode should be:
- upon entering a dynamic layer (aka Interpreter), we zero out all
dispatch keys* between FrontMode and BackMode
- then, the dynamic layer (aka Interpreter) decides to re-enable some
dispatch keys. For example, JVPInterpreter decides …
> Allow people to arbitrarily add dispatch keys between DynamicLayer{Front,Back}

- functorch/_src/eager_transforms.py
- functorch/csrc/DynamicLayer.cpp
- functorch/csrc/DynamicLayer.h
- functorch/csrc/init.cpp
- test/test_eager_transforms.py
Fixes #847
We do not allow users to call requires_grad_() inside a functorch
transform. This is because the user is effectively saying
"hey, I want another layer of autograd if I call requires_grad_()", but
that doesn't actually work because to set up a layer of autograd we need
to do some work (e.g. push autograd onto the DynamicLayerStack).
Instead, when a user calls requires_grad_() (and similarly retain_grad),
we raise a nice error message.
This has the intended consequence of causing
torch.autograd.functional.{jvp, vjp, jacobian} to error out when called
inside of a functorch transform. Users should use the functorch
equivalent.
Test Plan:
- added tests
> Disable calling Tensor.requires_grad_() inside a functorch transform

- functorch/csrc/BatchRulesLoss.cpp
- test/functorch_additional_op_db.py
- test/test_ops.py
Because MSE backward was redispatching, it ended up having some shape errors if it redispatched twice. This switches it to use the decomposition from core so that we don't try to guess based on the size of the input if it came from a redispatch or an original call. Specifically:
- when reduction != none, the original output would be of size [N]. We would be padding the grad_output with 1s if need be and then redispatching (with reduction == none). This led to issues because reduction == none assumes that grad output and self have the same number of elements
- when reduction == none, often times the grad_output would be flattened (a little unclear why this was happening, tbh). This was causing reshape errors. If we tried to fix this by just reshaping grad_output to match self, we would end …
> Fix MSE foward, use decomposition for MSE backward

- functorch/csrc/BatchRulesScatterOps.cpp
- test/functorch_additional_op_db.py
- test/test_ops.py
- test/test_vmap.py
Fixes https://github.com/pytorch/functorch/issues/859
Start reading at `NOTE: [advanced indexing (index.Tensor) batch rule]`
in the code for details. This PR rewrites the index.Tensor and index_put
batching rules.
The TL;DR is:
- advanced indexing has different behavior depending on if the "advanced
indices are adjacent":
https://numpy.org/doc/stable/user/basics.indexing.html#combining-advanced-and-basic-indexing
- we have to take this into account in our batching rules, because
index.Tensor and index_put handle these internally.
Test Plan
- I added new test cases for getitem and aten.ops.index_put via OpInfo
testing.
Future
- primtorch should have a sane decomposition that we can use
- We haven't fixed the index_put_ batching rule yet. TODO later...
- Upstream our test cases (see next …
> Fix index.Tensor, index_put batching rules

- docs/source/ux_limitations.rst
I want to be able to point someone at this page whenever we get asked
about the limitations of vmap. Please let me know if there are things
we're still missing from here
> Beef up transform limitations doc

- functorch/_src/aot_autograd.py
- test/test_pythonkey.py
With AMP, AOT Autograd traced graph already reflects the AMP modifications.
However, Torchscript does not know that, and can try to AMP-ify already AMP-ified AOTAutograd traced graph, resulting in weird type promotion errors.
Concern (and that's why WIP) - Calling `with` for each forward and backward pass, might add overhead. Is there any better way?
> Disable autocast

- functorch/csrc/BatchRulesHelper.h
- functorch/csrc/BatchedFallback.cpp
- functorch/csrc/LegacyBatchingRegistrations.cpp
- functorch/csrc/LegacyVmapTransforms.cpp
- functorch/csrc/LegacyVmapTransforms.h
- functorch/csrc/VmapModeRegistrations.cpp
- functorch/csrc/init.cpp
It's possible it is buggy and we should aim to delete the old batching
rule API in the future.
> Clearly mark the old batching rule API as "legacy"

- functorch/_src/monkey_patching.py
We don't need it anymore because we upstreamed the changes into
pytorch/pytorch a while ago.
> Remove cross_entropy monkey patch

- functorch/csrc/BatchRulesViews.cpp
To fully support expand.SymInt, we should write a batching rule for it.
Unfortunately, we are unable to write a batching rule because there are
not enough SymInt overloads (e.g. we need a view.SymInt, that doesn't
exist today).
This PR adds a decomp for expand.SymInt as a short-term fix.
> Fix expand.SymInt issues by adding a decomp

- notebooks/neural_tangent_kernels.ipynb
Hi and thanks for the great NTK tutorial in functorch - very exciting to have such effortless vmpa/jvps/vjps!
We have recently published a paper https://arxiv.org/abs/2206.08720 about our JAX empirical NTK implementations, where we analyze and compare their complexities, so I've added these updates and references to the tutorial as well. I also did some other minor changes (e.g. inner product -> outer product), hope these look ok.
FYI In the paper we also present a new third implementation (`Structured derivatives`) that we added recently (https://github.com/google/neural-tangents/blob/1e4754fb122ecab8ba2d2a3ca0379be824b4525d/neural_tangents/_src/empirical.py#L671), but it's quite complex to implement, so this should be left for another PR.
> Add complexities and references for NTK implementations.

- .github/workflows/wheels.yml
GHA seems to be installing universal2 Python 3.10, which is causing our
binary tag to say universal2 when it should be x86_64. This PR
attempts to get GHA to install an older version of Python 3.10
(in previous functorch releases we did not have this problem).
> Fix binaries tag (macos, Python 3.10)

- functorch/csrc/BatchedTensorImpl.h
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #924
[torchdim](https://github.com/facebookresearch/torchdim) reuses BatchTensorImpl objects
where it can across batched invocations, but needs to patch their levels to match
what _vmap_increment_nesting returns.
> Add _unsafe_set_level for torchdim

- .circleci/config.yml
- .circleci/unittest/linux/scripts/install.sh
- .circleci/unittest/windows/scripts/install.sh
- .github/workflows/wheels.yml
- functorch/__init__.py
- test/test_vmap.py
This PR:
- adds an error message when functorch is imported alongside a PyTorch
CUDA 10.2 binary (pip or conda)
- changes the CI to use cuda 11.3 for linux (since the error message
triggers no matter if it's a source build or binary build)
- Updates the links to PyTorch binaries to the officially released ones
instead of using the pytorch-test channel.
Test Plan:
- wait for tests
- manually test binaries offline
> Drop cuda 10.2 support for functorch 0.2.0 release

- test/common_utils.py
- test/test_ops.py
Previously, our vmap tests were generating 3^n tests per OpInfo sample.
For each tensor argument, we would generate all permutations of bdim =
(0, -1, None).
This is pretty redundant and also performance intensive. The original
purpose of this was to make sure functorch's batching rules work with
bdim other than 0 (it's really easy to forget that the bdim is not
always at the front of the tensor).
The new strategy is to generate all permutations of bdim = (-1, None)
and also include the case where all bdims are 0 as a sanity check.
This leads to 2^n tests.
On my machine test_vmap goes from 3m25s to 2m45s, which is promising.
However the biggest wins are going to be in test_ops where n can be as
high as 10.
> Generate 2^n tests, not 3^n tests for vmap

- functorch/csrc/BatchRulesDecompositions.cpp
- functorch/csrc/LegacyBatchingRegistrations.cpp
All the errors I'm seeing on CI are because `split.sizes` doesn't have a batch rule. This uses decompositions to register a batching rule for `split.sizes`
> (fix CI) Add batch rule for split.sizes

- functorch/csrc/PyTorchOperatorHacks.cpp
- test/test_ops.py
The jvp and vjp transforms should not change randomness behavior; e.g.
dropout under vjp and with regular PyTorch autograd should produce the
same values. vmap however does change randomness behavior.
This PR removes a bunch of randomness skips from jvp and vjp only tests
and also fixes our implementation of dropout such that it maintains the
above property.
Test Plan:
- run tests
> Remove removable randomness skips

- functorch/csrc/BatchRulesNorm.cpp
- test/common_utils.py
- test/test_ops.py
Follows the same idea as #937 but for batch norm and instance norm and does a little refactor to get rid of a TODO
In this something weird happened and it looks like we weren't testing fully for `vmapjvpall` with batch norm before...basically it's now failing because it's trying to differentiate wrt running_mean and running_var
Also this surfaced a typo in the batch norm batching rule and an issue where we were expanding running_mean or running_var without making them contiguous, caused errors when cuda tried to write to that tensor. Both of these errors were fixed in here to keep CI green
> Generate n^2 not n^3 inputs for batch and instance norm; small batch norm fix

- test/test_ops.py
For https://github.com/pytorch/pytorch/pull/80217.
https://github.com/pytorch/functorch/issues/961 is the tracking issue so
we don't forget to remove the skips.
> Add skips to coordinate land

- functorch/csrc/init.cpp
Richard left a comment here a while ago that I forgot about: https://github.com/pytorch/functorch/pull/235#discussion_r760258758
I had a crappy fix  for ensuring that `functionalize()` doesn't emit extra unnecessary `view_copy` ops that was actually wrong in some cases, but this should really fix it
> make sync logic more accurate for functionalization

- test/test_eager_transforms.py
Adding functionalization testing for some recent bug fixes:
- test that grad/vjp(functionalize(f)) works
- test that indexing gets functionalized properly - there was a subtle bug in the JIT type system that was preventing this from working, which should now be fixed (https://github.com/pytorch/pytorch/pull/76085)
> functionalize test hardening

- test/test_eager_transforms.py
There was a bug with JIT container types that caused a problem with List[Optional[Tensor]] arguments, that only actually surfaces in functorch (basically `libtorch.so` and `functorch.so` will each get their own static singleton instance of that type). Adding tests for it here.
companion core patch: https://github.com/pytorch/pytorch/pull/77846
> add functionalize index tests

- functorch/csrc/BatchRulesViews.cpp
This PR introduces `view.SymInt` overload to functorch ahead of time, so https://github.com/pytorch/pytorch/pull/81145 can pick it up and hopefully to not break functorch tests.
> add view.SymInt kernel

- functorch/_src/aot_autograd.py
Lower some overheads.
cc @Chillee
> Remove nn.Module from aot_module_simplified

- functorch/csrc/BatchRulesNorm.cpp
- test/common_utils.py
- test/test_ops.py
- test/test_vmap.py
Closes #867
This updates the batch norm check so that if we aren't training, we don't error since no inplace update will occur
The testing on this got messy. Now we can test ever combination of batching on the input, running_mean, and running_var (previously we only did a subset). 
Basically I knew that the only bool argument in an instance norm or batch norm call must be training because of the signature. So I looked for that in the kwargs. However, in the composition tests (like vmapvjp) the kwargs are captured by the vmap-ed over function, no longer inputs. So, this needed to refactor `get_fallback_and_vmap_exhaustive` to take a flag as to whether it's using a function that uses batch norm and that function is training instead of taking the opinfo and doing a name match on that. The …
> Allow batch norm with all variations of batching when training=False

- codegen/gen_vmap_plumbing.py
- functorch/csrc/BatchRulesDecompositions.cpp
- functorch/csrc/BatchRulesLinearAlgebra.cpp
- functorch/csrc/VmapGeneratedPlumbing.h
- test/test_vmap.py
Original code written by @kshitij12345 in
https://github.com/pytorch/functorch/pull/322,
this PR is just a rebase onto main
> [batch-rule] householder_product

- test/test_eager_transforms.py
We will need to disable these 4 expecttest tests until we land https://github.com/pytorch/pytorch/pull/81145
Failures:
https://github.com/pytorch/pytorch/runs/7398326290?check_suite_focus=true
> disable tests to land symint autograd changes

- functorch/csrc/BatchRulesNorm.cpp
- test/common_utils.py
- test/test_ops.py
- test/test_vmap.py
Adds two commits for batch norm bug fixes. From discussion on #273 and #867
cc @zou3519 I ended up cherry-picking two commits since #958 also caught a typo and need for a contiguous call. However, lines-wise, this ends up being a lot of testing changes. I think I can refactor both changes to have fewer testing changes but will end up looking different than the version on main. Any thoughts as to if I should keep it like this or try to refactor for fewer test changes?
> 0.2.1 batch norm fixes
