pytorch/functorch

functorch/_src/eager_transforms.py
functorch/_src/python_key.py
test/test_eager_transforms.py

Fixes https://github.com/zou3519/functorch/issues/5

adds support for grad if inputs don't depend on output

---

README.md
examples/dp_cifar10/cifar10_transforms.py
examples/ensembling/parallel_train.py
examples/maml_omniglot/maml-omniglot-ptonly.py
examples/maml_omniglot/maml-omniglot-transforms.py
examples/maml_regression/evjang_transforms_module.py
examples/nnc/linear_train.py
functorch/__init__.py
functorch/_src/eager_transforms.py
functorch/_src/make_functional.py
test/test_eager_transforms.py
test/test_pythonkey.py
test/test_vmap.py

Updates make_functional to use the new improved variants. The new
variants are superior in every way so we're replacing the previous
variants with this.
If someone wants the older variants, they can be found at:
- make_functional_with_buffers_deprecated_v1
- make_functional_deprecated_v1

[BC-breaking] Update make_functional*

---

.circleci/config.yml
.circleci/unittest/linux/scripts/environment.yml
.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/linux/scripts/post_process.sh
.circleci/unittest/linux/scripts/run_test.sh
.circleci/unittest/linux/scripts/setup_env.sh
codegen/codegen_outofplacebatching.py
functorch/csrc/BatchRulesConv.cpp
functorch/csrc/BatchRulesLinearAlgebra.cpp
test/test_ops.py

Scripts taken from pytorch/nestedtensor.

Setup circleci

---

.circleci/unittest/linux/scripts/run_test.sh

Run python key tests in CI

---

functorch/_src/eager_transforms.py
test/test_eager_transforms.py

Closes #110 
Adds ability to set which positional element we're getting the Jacobian with respect to (similar to [JAX](https://jax.readthedocs.io/en/latest/jax.html?highlight=jacrev#jax.jacrev))

Adding jacrev numargs argument

---

functorch/csrc/BatchRulesViews.cpp
functorch/csrc/BatchingRegistrations.cpp

Moves select's batching rule to use VMAP_SUPPORT and the rest of the new API

Move select batching rule to new API

---

functorch/_src/eager_compilation.py
test/test_pythonkey.py

Summary: The existing code assumed a single output; this generalizes to tuple
outputs
Test Plan: Compile a simple test program with multiple outputs and check that
outputs/grads are the same as eager.
```
def foo(a, b):
return a + b, a * b
```

Support functions with multiple outputs in `compiled_function`

---

functorch/csrc/BatchRulesModules.cpp
test/test_vmap.py

Adds batch rule for [grid sample](https://pytorch.org/docs/master/generated/torch.nn.functional.grid_sample.html#torch.nn.functional.grid_sample)

Grid sample batch rule registration

---

functorch/_src/vmap.py
test/test_vmap.py

Description:
- Added support for negative in_dims
- Added a basic test
Fixes #134

Added support for negative in_dims

---

functorch/csrc/BatchRulesReduceOps.cpp
functorch/csrc/BatchingRegistrations.cpp
test/test_ops.py

Description:
- Ported `_log_softmax` to the new API

Ported `_log_softmax` to the new API

---

test/test_ops.py

Description:
- Fixed unexpected failures with log_softmax

Fixed unexpected failures with log_softmax

---

.circleci/unittest/linux/scripts/run_test.sh

Description:
- Fixed `-v` position
https://app.circleci.com/pipelines/github/facebookresearch/functorch/280/workflows/0dc46a42-9680-4bb2-b64c-e3cd128f0c25/jobs/1656?invite=true#step-106-3900

Updated run_test.sh to make tests verbose

---

.circleci/unittest/linux/scripts/install.sh

Description:
- Fixes pytorch nightly cpu installation and should fix failing CI
Fixes #149

Fixes pytorch nightly cpu installation

---

functorch/csrc/BatchRulesModules.cpp
test/common_utils.py
test/test_ops.py
test/test_vmap.py

Description:
- Added cross batching rule
- Fixed issue in test/common_utils.py with repeated number 3 in dims. Set it to 4 and 2 to avoid special value for cross op
Related to #101

Added cross batching rule

---

functorch/csrc/BatchRulesReduceOps.cpp
functorch/csrc/BatchRulesStopDecomposition.cpp
test/functorch_lagging_op_db.py

Description:
- Added argsort batching rule

Added argsort batching rule

---

benchmarks/operator_authoring.py
functorch/__init__.py
functorch/_src/operator_authoring.py
test/test_pointwise_compile.py

This is the python component of the op-authoring-with-NNC/pointwise compiler prototype.  I've done nothing here except move it from core to functorch, so likely none of this runs as-is.  It's here purely so someone can tidy it up and land it properly!

Python pointwise compiler implementation

---

functorch/csrc/BatchRulesBinaryOps.cpp
functorch/csrc/BatchRulesLoss.cpp
functorch/csrc/BatchRulesStopDecomposition.cpp
test/test_ops.py
test/test_vmap.py

Reference: https://github.com/facebookresearch/functorch/issues/102

add cosine_similairity batching rule

---

functorch/_src/eager_transforms.py
functorch/_src/vmap.py

Description:
- Addresses #224
- Added docs for grad. 
- Cleaned unused imports and other nits

Added docstring for `grad`

---

functorch/_src/memory_efficient_op_authoring.py
functorch/compile/__init__.py
test/test_memory_efficient_operator_authoring.py

[Operator Authoring] Memory efficient pointwise fusion

---

functorch/_src/operator_authoring.py
functorch/csrc/PointwiseOperatorCompileCache.cpp
functorch/csrc/PointwiseOperatorCompileCache.h
functorch/csrc/init.cpp

Just cosmetic changes, no change in functionality.

Rename pointwise operator CompileCache to PointwiseOperatorCompileCache

---

test/test_eager_transforms.py

Description:
- Now device is used for severl CUDA tests that were running CPU tests instead
- device argument were unused

Fixed unused device in some test_eager_transforms tests

---

test/common_utils.py
test/test_pythonkey.py
test/test_vmap.py

Skip testing empty_like instead of xfail

---

functorch/_src/eager_transforms.py
test/test_eager_transforms.py

Also comes with a bugfix to argnums behavior and a lot of tests.

jacrev, multiple outputs support

---

functorch/_src/eager_transforms.py
test/test_eager_transforms.py

jvp transform accepts functions that take multiple inputs and outputs

---

functorch/_src/eager_transforms.py
functorch/csrc/BatchRulesDecompositions.cpp
test/test_eager_transforms.py

It's surprisingly a lot simpler than jacrev
Test Plan:
- new tests

jacfwd supports multiple inputs and outputs

---

functorch/csrc/BatchedFallback.cpp
functorch/csrc/DynamicLayer.cpp
functorch/csrc/DynamicLayer.h
test/test_eager_transforms.py

Fix edge case with in-place captures and grad transforms

---

functorch/csrc/BatchRulesDecompositions.cpp
functorch/csrc/BatchRulesNorm.cpp
test/test_vmap.py

layer_norm batch rule

---

functorch/_src/eager_transforms.py
test/test_eager_transforms.py

Test Plan:
- a lot of new tests

Update jacrev to accept functions with pytree inputs and outputs

---

functorch/csrc/BatchRulesBinaryOps.cpp
functorch/csrc/BatchRulesDynamic.cpp
functorch/csrc/BatchRulesFactory.cpp
test/test_ops.py
test/test_vmap.py

functorch jvp quick fixes

---

functorch/_src/eager_transforms.py
test/test_eager_transforms.py

jvp with pytree inputs

---

functorch/_src/eager_transforms.py
test/test_eager_transforms.py

jacfwd accepts pytree inputs

---

functorch/_src/eager_transforms.py
test/test_eager_transforms.py

jacobian / hessian correctness tests

---

functorch/csrc/BatchRulesScatterOps.cpp

replace reshape with view

---

benchmarks/ls_patterns/__init__.py
benchmarks/ls_patterns/benchmark_helper.py
benchmarks/ls_patterns/bias_dropout_res.py
benchmarks/ls_patterns/bias_gelu_dropout.py
benchmarks/ls_patterns/bias_relu_dropout.py

[Benchmarking] Adding scripts for lightseq benchmarking

---

benchmarks/ls_patterns/benchmark_helper.py
benchmarks/ls_patterns/bias_dropout_res_layernorm.py
benchmarks/ls_patterns/layernorm_sigmoid.py

[Benchmark] Layer norm patterns

---

functorch/csrc/BatchRulesLinearAlgebra.cpp
test/test_ops.py
test/test_vmap.py

Description:
- Added cholesky_solve op batch rule

Added cholesky_solve op batch rule

---

test/test_vmap.py

Description:
- Added tests for vmap and autocast on CUDA/CPU
- Note that tests are failing somehow on CPU
- Removed unused imports in test_vmap.py
Related to #305

Added tests for vmap and autocast

---

functorch/csrc/BatchRulesLinearAlgebra.cpp
test/test_vmap.py

Description:
- Added batch rule for LU op

Added batch rule for LU op

---

functorch/_src/eager_transforms.py
test/test_eager_transforms.py

Mitigates https://github.com/pytorch/functorch/issues/333 but we should
still consider whether or not we want a jacrev_and_value API.
Test Plan:
- New tests

Add `has_aux=False` to vjp, jacrev

---

functorch/csrc/BatchRulesFactory.cpp
test/test_ops.py
test/xfail_suggester.py

jvp transform fully composes with vmap

---

functorch/_src/aot_autograd.py
functorch/_src/fx_minifier.py
test/test_pythonkey.py

Used a Thunk approach, like in Autodidax.
I added some ugly microoptimizations since they save some amount of overhead.

Added support for output pytrees in AOTAutograd

---

functorch/csrc/BatchRulesDecompositions.cpp
functorch/csrc/BatchRulesModules.cpp
test/discover_coverage.py
test/functorch_additional_op_db.py
test/test_ops.py

Embedding backward batch rule

---

functorch/__init__.py
functorch/_src/eager_transforms.py
test/test_pythonkey.py

Also moved them out of the experimental namespace but added warning on
coverage.

More docs for jacfwd, hessian, jvp

---

gallery/README.rst
gallery/plot_ensembling.py
gallery/plot_jacobians_and_hessians.py
gallery/plot_per_sample_gradients.py
setup.cfg

Now we need to figure out how to visualize them

Wrote tutorials

---

benchmarks/ls_patterns/benchmark_helper.py

don't use sum for loss, arbitrary args in torch.Timer benchmarks

Small clean-ups for benchmark helper

---

README.md

The >>> is rather obnoxious when copy-pasting the examples.

README.md: don't include prompt in example code snippets

---

.circleci/config.yml

Fixes #378
Circle CI: https://app.circleci.com/pipelines/github/pytorch/functorch?branch=pull%2F379

Dropped 3.6 and added 3.9

---

functorch/_src/aot_autograd.py

Use num_bytes instead of numel in min-cut partitioning

---

test/test_vmap.py

Decription:
- Fixed CI unexpected success for cartesian_prod

Fixed CI unexpected success for cartesian_prod

---

functorch/_src/aot_autograd.py

Minor refactor for default partition.

---

functorch/__init__.py
functorch/csrc/BatchedTensorImpl.h
functorch/csrc/DynamicLayer.cpp
functorch/csrc/DynamicLayer.h
functorch/csrc/TensorWrapper.cpp
functorch/csrc/init.cpp
test/test_eager_transforms.py
test/test_vmap.py

Description:
- Hacky fix to fix printing tensors inside `grad`
- other nits and cosmetics
Fixes #382
@zou3519 what do you think ?

Fixes printing issue with TensorWrapper

---

functorch/csrc/BatchRulesScatterOps.cpp
test/test_vmap.py

Fixes: https://github.com/pytorch/functorch/issues/381
Handle broadcasting of `values` if the dimension shape after indexing is higher.
TODO : 
~~File an issue for code duplication~~

fix vmap : index_put_ (handle broadcasting of value)

---

functorch/csrc/CompileCache.cpp

For fixing https://github.com/pytorch/functorch/issues/430
@Chillee

Better error message for static argnums

---

functorch/csrc/BatchRulesScatterOps.cpp
test/functorch_additional_op_db.py
test/test_ops.py
test/test_vmap.py

Adds batching rule for `index_put`
This also fixes: #393

index_put : batch-rule

---

functorch/_src/decompositions.py

Decompose aten std op

---

benchmarks/transformer_fusion_patterns/benchmark.py
benchmarks/transformer_fusion_patterns/benchmark_helper.py
functorch/_src/aot_autograd.py
test/test_compile_cache.py

To handle https://github.com/pytorch/functorch/issues/430

Don't trace static_args 

---

functorch/_src/aot_autograd.py
functorch/_src/compilers.py
functorch/_src/partitioners.py
functorch/compile/__init__.py
test/test_pythonkey.py

Added Grad context to AOTAutograd

---

test/test_ops.py

Possible fix for CI speedup

---

functorch/csrc/BatchRulesBinaryOps.cpp
functorch/csrc/BatchRulesConvolution.cpp
functorch/csrc/BatchRulesFactory.cpp
functorch/csrc/BatchRulesHelper.h
functorch/csrc/BatchRulesLinearAlgebra.cpp
functorch/csrc/BatchRulesLoss.cpp
functorch/csrc/BatchRulesModules.cpp
functorch/csrc/BatchRulesNorm.cpp
functorch/csrc/BatchRulesPooling.cpp
functorch/csrc/BatchRulesReduceOps.cpp
functorch/csrc/BatchRulesScatterOps.cpp
functorch/csrc/BatchRulesUnaryOps.cpp
functorch/csrc/BatchRulesViews.cpp
writing_batching_rules.md

On the way to fixing https://github.com/pytorch/functorch/issues/417 ...

Split VMAP_SUPPORT macro into VMAP_SUPPORT/VMAP_SUPPORT2

---

functorch/csrc/BatchRulesLinearAlgebra.cpp
functorch/csrc/BatchRulesUnaryOps.cpp
functorch/csrc/BatchRulesViews.cpp
functorch/csrc/BatchingRegistrations.cpp

I wanted to leave these for easy intro tasks, but we are in need of this
cleanup.

Excise more legacy batching rules

---

examples/dp_cifar10/README.md
examples/dp_cifar10/cifar10_opacus.py
examples/dp_cifar10/cifar10_transforms.py
test/test_eager_transforms.py

Updates differential privacy example + test and adds small readme to that example's folder

Update differential privacy example

---

functorch/_src/aot_autograd.py

@Chillee PTAL
I used black to format as well.

Doc strings

---

examples/ensembling/parallel_train.py
examples/lennard_jones/lennard_jones.py
examples/maml_omniglot/maml-omniglot-transforms.py
examples/maml_regression/evjang.py
examples/maml_regression/evjang_transforms.py
examples/maml_regression/evjang_transforms_module.py

A number of small issues with the examples to make sure that they all run (and are able to run on GPU)

Fix small issues with examples

---

functorch/__init__.py

Add functorch.__version__

---

functorch/_src/vmap.py
functorch/csrc/BatchRulesRandomness.cpp
functorch/csrc/DynamicLayer.cpp
functorch/csrc/DynamicLayer.h
functorch/csrc/init.cpp

Fixes issues identified in #409

Cleanup from adding rand and randn PR

---

notebooks/aot_autograd_optimizations.ipynb

Rendered one - https://github.com/pytorch/functorch/blob/tutorial/notebooks/aot_autograd_optimizations.ipynb

Aot Autograd tutorial

---

functorch/_src/eager_transforms.py

Fixes https://github.com/pytorch/functorch/issues/502

Mention how to compute jacobian of f and output of f at the same time

---

functorch/csrc/BatchRulesDynamic.cpp
test/test_vmap.py

Description:
- Explicit error message when calling torch.where(x)
- Added a test
Related to https://github.com/pytorch/functorch/issues/445#issuecomment-1050946177

Explicit error message when calling torch.where(x)

---

test/test_ops.py

Using requires_grad as a proxy for "is this tensor differentiable" is
better than using all floating-point values because not all floating
point arguments may be differentiable.

Fix jvp testing

---

functorch/csrc/BatchRulesDecompositions.cpp
test/test_vmap.py

https://github.com/pytorch/functorch/issues/516

Convolution double backward batch rule

---

docs/source/_static/css/custom.css

Updated logo alignment

---

notebooks/aot_autograd_optimizations.ipynb

Fix the tutorial index

---

COMPILE_README.md

Added some description at the top and added doc and tutorial links.
I have not gone through major overhaul here. Not sure if its required.
@Chillee @zou3519

Compile readme

---

docs/source/ux_limitations.rst

Adds the following to the bottom of the "UX Limitations" page of the website

Add website note on randomness

---

.circleci/config.yml

Fixes https://github.com/pytorch/functorch/issues/496

Fixing deprecated circle-ci images

---

functorch/_src/eager_transforms.py
functorch/csrc/DynamicLayer.cpp
functorch/csrc/DynamicLayer.h
functorch/csrc/init.cpp
test/test_eager_transforms.py

Fixes https://github.com/pytorch/functorch/issues/592

Enable calling jvp inside autograd.Function

---

test/common_utils.py
test/discover_coverage.py

Too much entropy got into the old one so I rewrote the coverage
calculator. Haven't deleted the old one yet just in case we need to take
a look through it and debug differences, but I'm relatively confident in
the new one.

New coverage calculator

---

functorch/_src/make_functional.py
test/test_eager_transforms.py

Test Plan:
- a lot of new tests

make_functional parameter sharing fix

---

functorch/_src/make_functional.py
test/test_eager_transforms.py

Test Plan:
- a lot of new tests

make_functional parameter sharing fix (#620)

---

functorch/csrc/BatchRulesConvolution.cpp
functorch/csrc/BatchRulesModules.cpp
functorch/csrc/VmapGeneratedPlumbing.h

Introduced by https://github.com/pytorch/pytorch/commit/5375b2e994ee666996a47526c7f9629e85acfc54

fixed optionalarrayref breakages

---

functorch/csrc/DynamicLayer.cpp
test/test_eager_transforms.py

We add PythonTLSSnapshot to the local exclude while functorch is active
and remove it when we leave functorch. This is a quick fix; there's
something nicer we can do (which is refactor DynamicLayer to not have so
many RAII guards that modify the thread-local dispatcher state)

Apply functorch-side fix for PythonTLSSnapshot change

---

test/test_vmap.py

Adds tests for randomness ops where the batch dimension is not 0 (the first dimension)

Add non-first batch dim tests

---

functorch/csrc/BatchRulesBinaryOps.cpp
test/test_ops.py

Apparently gelu_backward doesn't broadcast well on mkldnn which is why we were seeing the other error

Fix gelu_backward

---

functorch/_src/compilers.py

Removing the hack to fix the avg_pool2d backward

---

functorch/_src/compilers.py
functorch/_src/decompositions.py

Add cudnn_batch_norm decomposition to default nvfuser decompositions

---

functorch/csrc/BatchRulesRandomness.cpp
test/test_vmap.py

Fix multinomial

---

functorch/_src/compilers.py

Handle -inf for Fx to TS

---

functorch/csrc/BatchRulesActivation.cpp
test/test_ops.py
test/test_vmap.py

[Release] Prelu batching rule (forward + backward)

---

functorch/csrc/BatchRulesBinaryOps.cpp
test/test_vmap.py

Both are bugs with pytorch, have been filed. Batching them together since they're both such small changes

Fix normal_ and bernoulli

---

functorch/csrc/BatchRulesNorm.cpp
test/test_ops.py

[Release] fix group norm, add scaffolding for autograd.grad tests

---

functorch/csrc/BatchRulesRandomness.cpp
test/test_vmap.py

[Release] fix multinomial

---

test/test_ops.py

There's a lot so pushing to a branch to check I didn't miss any

Delete now passing tests

---

functorch/_src/python_key.py
test/test_pythonkey.py

Skip extracting meta tensor info for sparse tensors

---

docs/source/index.rst
notebooks/whirlwind_tour.ipynb

For our docs landing page.
Fixes https://github.com/pytorch/functorch/issues/605

Better intro to functorch

---

test/test_pythonkey.py

This test now works after https://github.com/pytorch/pytorch/pull/75827

Fix test following tls update in core

---

functorch/_src/vmap.py
test/test_ops.py
test/test_pythonkey.py

Fixes https://github.com/pytorch/functorch/issues/713

Cleanup return_types handling now that it has been upstreamed

---

functorch/csrc/DynamicLayer.cpp

Make it clearer what logic is being applied for what transform.

Refactor dynamicLayerFrontFallback

---

functorch/csrc/ADInterpreters.cpp
functorch/csrc/ADInterpreters.h
functorch/csrc/DynamicLayer.cpp
functorch/csrc/DynamicLayer.h
functorch/csrc/FunctionalizeInterpreter.cpp
functorch/csrc/FunctionalizeInterpreter.h
functorch/csrc/Interpreter.cpp
functorch/csrc/Interpreter.h
functorch/csrc/VmapInterpreter.cpp
functorch/csrc/VmapInterpreter.h

See functorch/csrc/Interpreter.h for the rundown of what happened.

Refactor DynamicLayer so the logic for each transform is separate

---

functorch/csrc/ADInterpreters.cpp
functorch/csrc/BatchingRegistrations.cpp
functorch/csrc/VmapTransforms.cpp

Fix some warnings by static analyzer

Fix some minor issues

---

functorch/_src/eager_transforms.py

Useful hedge if there are decompositions that can't be torchscripted.

Add option to simply use torchscript to call back into python lol

---

.github/workflows/lint.yml
.lintrunner.toml
tools/lint/black_linter.py
tools/lint/flake8_linter.py
tools/lint/pip_init.py

Black and flake8 for now + workflow in CI
Your codebase is not clean for either, so either fix em all or define
exclusions.
You can run lint on all files by doing
```
git grep -Il . | xargs lintrunner
```
You can autoformat all files by doing
```
git grep -Il . | xargs lintrunner f
```

add lintrunner support

---

functorch/csrc/BatchRulesLoss.cpp
functorch/csrc/BatchRulesViews.cpp
functorch/csrc/CustomFunction.cpp
functorch/csrc/PlumbingHelper.cpp

Some minor fixes found by static analyzer

Minor fix2

---

examples/compilation/fuse_module.py
examples/compilation/linear_train.py
examples/compilation/simple_function.py

update import for compile examples

update compile example imports

---

.circleci/unittest/linux/scripts/install.sh
test/test_ops.py
test/test_vmap.py

Moving back to conda after it failed to build for a day. Seems like a transient problem

Fix cuda tests, skip mac unexpected successes

---

examples/dp_cifar10/cifar10_transforms.py

see [this issue](https://github.com/pytorch/functorch/issues/467)
With this fix, I am able to train with increasing accuracy. A snapshot of the result is as follows:
Train Epoch: 1 	 Loss: 15.041652 Acc@1: 0.100627
Train Epoch: 2 	 Loss: 4.124658 Acc@1: 0.131835
Train Epoch: 3 	 Loss: 4.547704 Acc@1: 0.139376
Train Epoch: 4 	 Loss: 3.026205 Acc@1: 0.164505
Train Epoch: 15 	 Loss: 2.361405 Acc@1: 0.187484
Train Epoch: 20 	 Loss: 2.129503 Acc@1: 0.204000
Train Epoch: 25 	 Loss: 2.258233 Acc@1: 0.196963
Train Epoch: 30 	 Loss: 2.093566 Acc@1: 0.227712
Train Epoch: 35 	 Loss: 2.112152 Acc@1: 0.237524
Train Epoch: 40 	 Loss: 2.022015 Acc@1: 0.265369
Train Epoch: 45 	 Loss: 1.975909 Acc@1: 0.277382
Train Epoch: 50 	 Loss: 1.988672 Acc@1: 0.280977
Train Epoch: 55 	 Loss: 1.921672 Acc@1: 0.302930 …

fix dp-sgd example

---

functorch/_src/aot_autograd.py
functorch/_src/partitioners.py

(also made output order of saved tensors deterministic).

fixed some issues with setting leaves and made partitioning deterministic

---

functorch/_src/aot_autograd.py
test/test_pythonkey.py

Present Random state

---

test/discover_coverage.py
test/functorch_additional_op_db.py
test/test_ops.py

- deleted test_vmapjvp (test_vmapjvpall is a superset of test_vmapjvp)
- added additional_op_db to things tested by test_vmapjvpall
- did some accounting in discover_coverage

Cleanup jvp testing

---

test/test_eager_transforms.py

We just needed to update the expecttest because we changed to
representing overloads in the graph

Fix functionalize failures

---

functorch/_src/aot_autograd.py
functorch/_src/config.py
functorch/compile/__init__.py
test/test_functionalize.py

PR for collaboration and hunting down bugs.

Use Functionalization pass and guard with a global config flag

---

benchmarks/chrome_trace_parser.py
functorch/_src/benchmark_utils.py

Refactor the code to have a single command that first create the chrome traces, and then parse it to get the GPU Utilization. 
Add doc string.

refactor code, add docstring

---

codegen/gen_vmap_plumbing.py
functorch/csrc/BatchRulesScatterOps.cpp
functorch/csrc/VmapGeneratedPlumbing.h
test/functorch_additional_op_db.py
test/test_ops.py
test/test_vmap.py

Related to https://github.com/pytorch/functorch/issues/957
It's difficult to write a batching rule for masked_fill.Tensor, so I
didn't write one for that.

masked_fill.Scalar batch rule

---

test/test_ops.py

remove kl_div skips
